In [4]:
#Python needs to know that we want to use nUmPy (Numerical Python)
import numpy as np

# 1. Numpy Arrays

1. An array is a data structure that stores the values of same data type.
2. While python lists can contain values corresponding to different data types, arrays in python can only contain values correspondong to the same data type.
3. Python lists fail to deliver the performance required while computing large sets of numerical data. To address this issue, we use numpy Arrays.
4. We can create NumPy arrays by converting list to an array.


In [12]:
#defining a list of different car co
arr_str = ['Meredes', 'BMW', 'Audi', 'Ferrrari', 'Tesla']

#defining a list f number of cylinders in the car
arr_num = [4, 6, 8, 10, 12]

#conversion of the python list to python array using numPy
new_arr_str = np.array(arr_str)

#conversion of the python list to python array using numPy
new_arr_num = np.array(arr_num)

print("After conversion of list to array", new_arr_str)
print("After conversion of list to array", new_arr_num)

#Let's print the data type of both the lists and arrays
print("Data type of list arr_str is:", type(arr_str))
print("Data type of array new_arr_str is:", type(new_arr_str))
print("Data type of list arr_num is:", type(arr_num))
print("Data type of array new_arr_num is:", type(new_arr_num))

After conversion of list to array ['Meredes' 'BMW' 'Audi' 'Ferrrari' 'Tesla']
After conversion of list to array [ 4  6  8 10 12]
Data type of list arr_str is: <class 'list'>
Data type of array new_arr_str is: <class 'numpy.ndarray'>
Data type of list arr_num is: <class 'list'>
Data type of array new_arr_num is: <class 'numpy.ndarray'>


# 2. Numpy Matrix

1. A matrix is a 2 dimensional data structure where elements are arranged in rows and columns.
2. A matrix can be created by using list of lists.

In [15]:
# Let's say we have information on different cylinders in a car and we want to display them in matrix format.
matrix = np.array([[1,2,1], [4,5,9], [6,7,8]])
print(matrix)
print("Data type of the matrix is ", type(matrix))

[[1 2 1]
 [4 5 9]
 [6 7 8]]
Data type of the matrix is  <class 'numpy.ndarray'>


# 3. NumPy Functions
There are different ways to create NUmPy Arrays using functions available in NumPy Library
## Using np.arange() function
1. The np.arange() function returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. start is included but stop is excluded.
2. It has the following parameters

    start: start of the interval range. Default = 0
    stop : end of internal range
    step : step size of the internal range. Default = 1

In [17]:
arr2 = np.arange(start = 0, stop = 10, step = 2)
print(arr2)

[0 2 4 6 8]


## Using np.linspace() function
The np.linspace() function returns the numbers which are evenly distributed with respect to the interval. Here, the start and stop both are included.
It has the same following parameters:

    start: Is the start of the interval range, default = 0.
    stop : Is the end of the interval range.
    num. : No. of samples to generate. Default = 50

In [18]:
matrix2 = np.linspace(0,5)
print(matrix2)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


### How are these values getting generated?
    The step size or the difference between each element is decided by the following formula:

    (stop-start)/(total elements - 1)
    so here it is, (5-0)/49 = 1.10204082

# 4. Using np.zeros() function

    - The np.zeros() is a function for creating a matrix and performing matrix operations in NumPy.
    - It returns a matrix filled with zeros of the given shape.
    - It has the following parameters:

        shape: Number of rows and columns in the matrix.
        dtype: data type of the elements in the matrix, by default it is set to float. 

In [20]:
matrix4 = np.zeros([3,5], dtype = int)
print(matrix4)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# 5. Using np.ones() function
    - it is same as np.zeros(), it just prints 1 instead of 0.

In [22]:
matrix5 = np.ones([3,5])
print(matrix5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# 6. Using np.eye() function
    - The np.eye() function for creating a matrix and performing matrix operations in NumPy.
    - It returns a matrix with ones on the diagonal and zeros elsewhere.

    It has following parameters:

    n : Number of rows and columns in the output matrix.
    dtype: data type of the elements in the matrix, by default it is set to float.

In [23]:
matrix6 = np.eye(5)
print(matrix6)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Conversion of one dimensionsl array to a matrix.
    This can be done using np.reshape() function

    The shape of an array basically tells the number of elements and dimensions in the array. Reshaping a NumPy array simply means changing the shape of the given array.

    By reshaping an array, we can add or remove dimensionsor change number of elements in each dimension.


In [25]:
print(np.reshape(arr_num, (5,1)))

[[ 4]
 [ 6]
 [ 8]
 [10]
 [12]]


# Arithmetic Operations on Arrays

In [26]:
l1 = [1,2,3]
l2 = [4,5,6]
print(l1 + l2)

[1, 2, 3, 4, 5, 6]


In [31]:
# Checking operations on arrays

arr7 = np.arange(1,6)
print("Array 7: ", arr7)

arr8 = np.arange(3,8)
print("Array 8: ", arr8)

print("Addition: ", arr7 + arr8)
print("Subtraction: ", arr7 - arr8)
print("Multiplication: ", arr7 * arr8)
print("Division: ", arr7/arr8)
print("Inverse of Array 7: ", 1/arr7)
print("Inverse of Array 8: ", 1/arr8)
print("Powers: ", arr7 ** arr8)

Array 7:  [1 2 3 4 5]
Array 8:  [3 4 5 6 7]
Addition:  [ 4  6  8 10 12]
Subtraction:  [-2 -2 -2 -2 -2]
Multiplication:  [ 3  8 15 24 35]
Division:  [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse of Array 7:  [1.         0.5        0.33333333 0.25       0.2       ]
Inverse of Array 8:  [0.33333333 0.25       0.2        0.16666667 0.14285714]
Powers:  [    1    16   243  4096 78125]


### Expression arr(::-1) reverses the array.

# OPERATIONS ON NUMPY MATRIX

In [33]:
matrix7 = np.arange(1,10).reshape(3,3)
print("Matrix 7: \n", matrix7)

matrix8 = np.eye(3)
print("Matrix 8: \n", matrix8)

Matrix 7: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 8: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
print("Addition: \n", matrix7 + matrix8)
print("Subtraction: \n", matrix7 - matrix8)
print("Multiplication: \n", matrix7 * matrix8)
print("Division: \n", matrix7 / matrix8)
print("Inverse of Matrix 7: \n", np.linalg.inv(matrix7))
print("Inverse of Matrix 8: \n", np.linalg.inv(matrix8))
print("Powers: \n", matrix7 ** 2)

Addition: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Subtraction: 
 [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division: 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]
Inverse of Matrix 7: 
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
Inverse of Matrix 8: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Powers: 
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


/var/folders/gq/12rz5dvx5fb1dsm_zy618x0h0000gn/T/ipykernel_2510/3528002546.py:4: RuntimeWarning: divide by zero encountered in divide
  print("Division: \n", matrix7 / matrix8)


1. Run Time Error is an error which occurs during the program execution after successful compilation.
2. One of the most common run time errors are:
    1. Division by Error: Due to division by error, we usually get inf (which means infinity) values because 1/0 is not a defined operation

# LINEAR ALGEBRA MATRIX MULTIPLICATION

In [35]:
matrix9 = np.arange(1,10).reshape(3,3)
print("First Matrix: \n", matrix9)

matrix10 = np.arange(11,20).reshape(3,3)
print("Second Matrix: \n", matrix10)
print(' ')

#Taking linear Algebra Matrix Multiplication (some may also call it as Dot Product)
print("Multiplication: \n", matrix9 @ matrix10)

First Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix: 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
 
Multiplication: 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


# Transpose of a Matrix

In [40]:
matrix11 = np.arange(1,10).reshape(3,3)
matrix12 = np.transpose(matrix11)
print("Original Matrix: \n", matrix11)
print("Transposed Matrix: \n", matrix12)

matrix13 = matrix11.T
print(matrix13)

Original Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed Matrix: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Functions to find Minimum and Maximum of Matrix


In [38]:
print("Minimum Value: \n", np.min(matrix11))
print("Maximum Value: \n", np.max(matrix11))

Minimum Value: 
 1
Maximum Value: 
 9
